"""empty message

Revision ID: 4aeb195624eb
Revises: a335f2c4499a
Create Date: 2024-02-07 14:46:47.254675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4aeb195624eb'
down_revision = 'a335f2c4499a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_invoicing_api', sa.String(length=100), nullable=True))

    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_invoicing_api', sa.String(length=100), nullable=True))

    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id_invoicing_api', sa.String(length=100), nullable=True))

    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id_invoicing_api', sa.String(length=100), nullable=True))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_link', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('new_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('meet_link')

    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.drop_column('client_id_invoicing_api')

    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.drop_column('product_id_invoicing_api')

    with op.batch_alter_table('assistant', schema=None) as batch_op:
        batch_op.drop_column('user_id_invoicing_api')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('user_id_invoicing_api')

    # ### end Alembic commands ###
