"""completed

Revision ID: 29ca84dad37b
Revises: cca2296b8c96
Create Date: 2025-02-28 15:04:41.087759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ca84dad37b'
down_revision = 'cca2296b8c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('words_learned', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.drop_column('words_learned')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
