"""empty message

Revision ID: 634199115db3
Revises: 29ca84dad37b
Create Date: 2025-03-04 13:06:20.308230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634199115db3'
down_revision = '29ca84dad37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
