"""date

Revision ID: cca2296b8c96
Revises: a335f2c4499a
Create Date: 2025-02-28 11:39:18.930832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cca2296b8c96'
down_revision = 'a335f2c4499a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.Date(), nullable=True))

    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('new_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.drop_column('public')

    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###
